services:
  - type: web
    name: smarteats-api
    env: python
    buildCommand: pip install Flask Flask-CORS gunicorn
    startCommand: gunicorn app:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
