services:
  - type: web
    name: smarteats-api
    env: python
    buildCommand: pip install Flask Flask-CORS gunicorn Flask-SQLAlchemy Flask-JWT-Extended
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
